name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with full history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This is CRITICAL for git pull to work

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Pull latest remote changes with rebase
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git pull --rebase origin master || true

        git add .
        git commit -m "Automated update of talk locations" || echo "No changes to commit"

        # Push only if there were changes
        git diff --quiet && git diff --cached --quiet || git push origin master

