name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install getorg --upgrade

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          # Set authenticated remote URL
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
      
          # Make sure we're on the correct branch
          git checkout master
      
          # Fetch and rebase from origin/master to prevent non-fast-forward error
          git fetch origin
          git rebase origin/master || true
      
          # Commit changes (only if there are any)
          git add .
          git commit -m "Automated update of talk locations" || echo "No changes to commit"
      
          # Push safely to origin/master
          git push origin master

