name: Scrape Talk Locations
on:
  push:
    branches: [ master ]
    paths:
      - 'talks/**'
      - 'talkmap.ipynb'
jobs:
  update-talk-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history to allow rebasing
          ref: master     # ensure we are on the master branch
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install jupyter pandas requests beautifulsoup4 geopy
          pip install getorg --upgrade
      - name: Run Jupyter Notebook to update talks
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automated update of talk locations" || echo "No changes to commit"
      - name: Rebase onto latest master
        run: |
          git fetch origin master
          git rebase origin/master
      - name: Push updates
        run: git push origin HEAD:master
